name: Feature request
description: Suggest an idea for this project
title: "[FEATURE] <Enter a title for your feature here>"
labels: [ "enhancement" ]
assignees: [ Lysagxra ]

body:
  - type: textarea
    id: feature-description

    attributes:
      label: Describe the feature you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: "Example: I would like the tool to include an option for automatic updates."
    
    validations:
      required: true
      
  - type: textarea
    id: problem-related

    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "Example: I'm always frustrated when..."

    validations:
      required: false

  - type: textarea
    id: alternatives-considered

    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: "Example: I’ve tried using a script to automate updates, but it doesn’t always work properly"

    validations:
      required: false

  - type: textarea
    id: additional-context

    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: "Example: Here is a screenshot of the tool in action and how it could benefit from automatic updates."

    validations:
      required: false
